name: Talisman integration

on:
  push:
    branches:
      - main

jobs:
  talisman_scan:
    name: Run Talisman Scan on History and Current Files
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Talisman
      - name: Install Talisman
        run: |
          curl -L https://thoughtworks.github.io/talisman/install.sh | bash

      # Ensure .git/hooks exists and Talisman pre-push hook is installed correctly
      - name: Create .git/hooks directory and set permissions
        run: |
          mkdir -p ~/.git/hooks  # Ensure the .git/hooks directory exists
          chmod +x ~/.git/hooks/pre-push  # Set executable permission for pre-push hook

      # Run Talisman scan
      - name: Run Talisman Scan on History and Current Files
        run: |
          talisman --scan-history --scan-all --output-format text > talisman-report.txt

      # Display the Talisman report in the logs
      - name: Display Talisman Report
        run: |
          cat talisman-report.txt

      # Optional: Upload the report as an artifact
      - name: Upload Talisman Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: talisman-report
          path: talisman-report.txt

    
