name: Talisman integration

on:
  push:
    branches:
      - main

jobs:
  talisman_scan:
    name: Run Talisman Scan on History and Current Files
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Talisman
      - name: Install Talisman
        run: |
          curl https://thoughtworks.github.io/talisman/install.sh > /tmp/install-talisman.sh
          chmod +x /tmp/install-talisman.sh
          pwd
          echo "poloooo"
          ls
          bash /tmp/install-talisman.sh pre-commit
          bash /tmp/install-talisman.sh pre-push
    
      # Run Talisman scan
      - name: Run Talisman Scan on History and Current Files
        run: |
          talisman --scan text > talisman-report.txt

      # Display the Talisman report in the logs
      - name: Display Talisman Report
        run: |
          cat talisman-report.txt

      # Optional: Upload the report as an artifact
      - name: Upload Talisman Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: talisman-report
          path: talisman-report.txt

    
