name: Talisman integration

on:
  push:
    branches:
      - main

jobs:
  build_and_analyze:
    name: Build, Analyze, and Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Talisman and Save Report
        run: |
          curl -L https://thoughtworks.github.io/talisman/install.sh | bash
          chmod +x .git/hooks/pre-push
          .git/hooks/pre-push --scan . > talisman-report.txt
        continue-on-error: true

      - name: Upload Talisman Report
        uses: actions/upload-artifact@v3
        with:
          name: talisman-report
          path: talisman-report.txt

    
