name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
 deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_IP: ${{ secrets.EC2_IP }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add EC2 host to known hosts
      env:
        EC2_IP: ${{ secrets.EC2_IP }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync -avz --exclude='.git' . ubuntu@$EC2_IP:/var/www/
